//------------------------------------------------------------------------------
// alpha_polyline_shaders.h - Alpha-blended polyline shaders (header-only)
//
// Renders thick polylines with alpha blending and miter-adjusted joins.
// Contains 3 shader pairs for different polyline components:
//
// 1. Intermediate segments (4 points: pA, pB, pC, pD)
//    - Middle segments with miter at both ends to prevent overlap
//
// 2. Terminal segments (3 points: pA, pB, pC)
//    - First/last segments with miter at one end, flat at the other
//
// 3. Pie-slice joins (3 points: pA, pB, pC)
//    - Fills the angular gap at bends with arc geometry
//
// Based on: https://wwwtyro.net/2021/10/01/instanced-lines-part-2.html
//------------------------------------------------------------------------------
#ifndef ALPHA_POLYLINE_SHADERS_H
#define ALPHA_POLYLINE_SHADERS_H

//------------------------------------------------------------------------------
// Metal Shading Language
//------------------------------------------------------------------------------
#if defined(SOKOL_METAL)

//--- Intermediate segment shader (miter at both ends) ---
static const char* alpha_intermediate_segment_vs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct vs_in {\n"
    "    float3 template_pos [[attribute(0)]];\n"
    "    float3 pA [[attribute(1)]];\n"
    "    float3 pB [[attribute(2)]];\n"
    "    float3 pC [[attribute(3)]];\n"
    "    float3 pD [[attribute(4)]];\n"
    "    float4 color [[attribute(5)]];\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 pos [[position]];\n"
    "    float4 color;\n"
    "};\n"
    "struct vs_params {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "};\n"
    "vertex vs_out vs_main(vs_in in [[stage_in]], constant vs_params& params [[buffer(0)]]) {\n"
    "    vs_out out;\n"
    "    \n"
    "    float4 clipA = params.mvp * float4(in.pA, 1.0);\n"
    "    float4 clipB = params.mvp * float4(in.pB, 1.0);\n"
    "    float4 clipC = params.mvp * float4(in.pC, 1.0);\n"
    "    float4 clipD = params.mvp * float4(in.pD, 1.0);\n"
    "    \n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    float2 ndcD = clipD.xy / clipD.w;\n"
    "    \n"
    "    ndcA.x *= params.aspect_ratio;\n"
    "    ndcB.x *= params.aspect_ratio;\n"
    "    ndcC.x *= params.aspect_ratio;\n"
    "    ndcD.x *= params.aspect_ratio;\n"
    "    \n"
    "    float2 p0, p1, p2;\n"
    "    float2 pos = float2(in.template_pos.z, in.template_pos.y);\n"
    "    float4 baseClip;\n"
    "    \n"
    "    if (in.template_pos.z < 0.5) {\n"
    "        p0 = ndcA; p1 = ndcB; p2 = ndcC;\n"
    "        baseClip = clipB;\n"
    "    } else {\n"
    "        p0 = ndcD; p1 = ndcC; p2 = ndcB;\n"
    "        pos = float2(1.0 - in.template_pos.z, -in.template_pos.y);\n"
    "        baseClip = clipC;\n"
    "    }\n"
    "    \n"
    "    float2 d01 = p1 - p0;\n"
    "    float2 d21 = p1 - p2;\n"
    "    float2 d12 = p2 - p1;\n"
    "    \n"
    "    float len01 = length(d01);\n"
    "    float len12 = length(d12);\n"
    "    \n"
    "    float2 dir01 = (len01 > 0.0001) ? d01 / len01 : float2(1.0, 0.0);\n"
    "    float2 dir12 = (len12 > 0.0001) ? d12 / len12 : float2(1.0, 0.0);\n"
    "    \n"
    "    float2 tangentSum = dir01 + dir12;\n"
    "    float tangentLen = length(tangentSum);\n"
    "    float2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : float2(-dir01.y, dir01.x);\n"
    "    \n"
    "    float2 normal = float2(-tangent.y, tangent.x);\n"
    "    float2 p01Norm = float2(-dir01.y, dir01.x);\n"
    "    \n"
    "    float sigma = sign(dot(d01 + d21, normal));\n"
    "    if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "    \n"
    "    float dotNP = dot(normal, p01Norm);\n"
    "    float minDot = 0.1;\n"
    "    if (abs(dotNP) < minDot) {\n"
    "        dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "    }\n"
    "    \n"
    "    float2 offset;\n"
    "    float halfWidth = params.line_width * 0.5;\n"
    "    \n"
    "    if (sign(pos.y) == -sigma) {\n"
    "        float2 miterOffset = normal * (-sigma) * halfWidth / dotNP;\n"
    "        offset = miterOffset;\n"
    "    } else {\n"
    "        float2 yBasis = float2(-dir12.y, dir12.x);\n"
    "        offset = yBasis * params.line_width * pos.y;\n"
    "    }\n"
    "    \n"
    "    offset.x /= params.aspect_ratio;\n"
    "    \n"
    "    out.pos = baseClip;\n"
    "    out.pos.xy += offset * baseClip.w;\n"
    "    out.color = in.color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_intermediate_segment_fs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct fs_in {\n"
    "    float4 color;\n"
    "};\n"
    "fragment float4 fs_main(fs_in in [[stage_in]]) {\n"
    "    return in.color;\n"
    "}\n";

//--- Terminal segment shader (miter at one end) ---
static const char* alpha_terminal_segment_vs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct vs_in {\n"
    "    float3 template_pos [[attribute(0)]];\n"
    "    float3 pA [[attribute(1)]];\n"
    "    float3 pB [[attribute(2)]];\n"
    "    float3 pC [[attribute(3)]];\n"
    "    float4 color [[attribute(4)]];\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 pos [[position]];\n"
    "    float4 color;\n"
    "};\n"
    "struct vs_params {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "};\n"
    "vertex vs_out vs_main(vs_in in [[stage_in]], constant vs_params& params [[buffer(0)]]) {\n"
    "    vs_out out;\n"
    "    \n"
    "    float4 clipA = params.mvp * float4(in.pA, 1.0);\n"
    "    float4 clipB = params.mvp * float4(in.pB, 1.0);\n"
    "    float4 clipC = params.mvp * float4(in.pC, 1.0);\n"
    "    \n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= params.aspect_ratio;\n"
    "    ndcB.x *= params.aspect_ratio;\n"
    "    ndcC.x *= params.aspect_ratio;\n"
    "    \n"
    "    float2 dAB = ndcB - ndcA;\n"
    "    float lenAB = length(dAB);\n"
    "    float2 dirAB = (lenAB > 0.0001) ? dAB / lenAB : float2(1.0, 0.0);\n"
    "    \n"
    "    float2 perp = float2(-dirAB.y, dirAB.x);\n"
    "    \n"
    "    float halfWidth = params.line_width * 0.5;\n"
    "    float2 offset;\n"
    "    float4 baseClip;\n"
    "    \n"
    "    if (in.template_pos.z < 0.5) {\n"
    "        baseClip = clipA;\n"
    "        offset = perp * params.line_width * in.template_pos.y;\n"
    "    } else {\n"
    "        baseClip = clipB;\n"
    "        \n"
    "        float2 dBC = ndcC - ndcB;\n"
    "        float lenBC = length(dBC);\n"
    "        float2 dirBC = (lenBC > 0.0001) ? dBC / lenBC : float2(1.0, 0.0);\n"
    "        \n"
    "        float2 tangentSum = dirAB + dirBC;\n"
    "        float tangentLen = length(tangentSum);\n"
    "        float2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : float2(-dirAB.y, dirAB.x);\n"
    "        \n"
    "        float2 normal = float2(-tangent.y, tangent.x);\n"
    "        float2 abNorm = float2(-dirAB.y, dirAB.x);\n"
    "        \n"
    "        float2 ab = dAB;\n"
    "        float2 cb = -dBC;\n"
    "        float sigma = sign(dot(ab + cb, normal));\n"
    "        if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "        \n"
    "        float dotNP = dot(normal, abNorm);\n"
    "        float minDot = 0.1;\n"
    "        if (abs(dotNP) < minDot) {\n"
    "            dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "        }\n"
    "        \n"
    "        float posY = in.template_pos.y;\n"
    "        \n"
    "        if (sign(posY) == -sigma) {\n"
    "            offset = 0.5 * normal * (-sigma) * params.line_width / dotNP;\n"
    "        } else {\n"
    "            float2 yBasis = float2(-dirAB.y, dirAB.x);\n"
    "            offset = yBasis * params.line_width * posY;\n"
    "        }\n"
    "    }\n"
    "    \n"
    "    offset.x /= params.aspect_ratio;\n"
    "    \n"
    "    out.pos = baseClip;\n"
    "    out.pos.xy += offset * baseClip.w;\n"
    "    out.color = in.color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_terminal_segment_fs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct fs_in {\n"
    "    float4 color;\n"
    "};\n"
    "fragment float4 fs_main(fs_in in [[stage_in]]) {\n"
    "    return in.color;\n"
    "}\n";

//--- Pie-slice join shader (fills angular gaps) ---
static const char* alpha_pie_join_vs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct vs_in {\n"
    "    float3 template_pos [[attribute(0)]];\n"
    "    float3 pA [[attribute(1)]];\n"
    "    float3 pB [[attribute(2)]];\n"
    "    float3 pC [[attribute(3)]];\n"
    "    float4 color [[attribute(4)]];\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 pos [[position]];\n"
    "    float4 color;\n"
    "};\n"
    "struct vs_params {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "    float join_resolution;\n"
    "    float miter_angle_limit;\n"
    "};\n"
    "\n"
    "vertex vs_out vs_main(vs_in in [[stage_in]], constant vs_params& params [[buffer(0)]]) {\n"
    "    vs_out out;\n"
    "    const float PI = 3.14159265359;\n"
    "    \n"
    "    float4 clipA = params.mvp * float4(in.pA, 1.0);\n"
    "    float4 clipB = params.mvp * float4(in.pB, 1.0);\n"
    "    float4 clipC = params.mvp * float4(in.pC, 1.0);\n"
    "    \n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= params.aspect_ratio;\n"
    "    ndcB.x *= params.aspect_ratio;\n"
    "    ndcC.x *= params.aspect_ratio;\n"
    "    \n"
    "    float2 dirBC = ndcC - ndcB;\n"
    "    float2 dirBA = ndcA - ndcB;\n"
    "    float lenBC = length(dirBC);\n"
    "    float lenBA = length(dirBA);\n"
    "    \n"
    "    if (lenBC < 0.0001 || lenBA < 0.0001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = in.color;\n"
    "        return out;\n"
    "    }\n"
    "    \n"
    "    float2 normBC = dirBC / lenBC;\n"
    "    float2 normBA = dirBA / lenBA;\n"
    "    \n"
    "    float2 xBasisSum = normBC - normBA;\n"
    "    float xBasisLen = length(xBasisSum);\n"
    "    \n"
    "    if (xBasisLen < 0.0001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = in.color;\n"
    "        return out;\n"
    "    }\n"
    "    \n"
    "    float2 xBasis = xBasisSum / xBasisLen;\n"
    "    float2 yBasis = float2(-xBasis.y, xBasis.x);\n"
    "    \n"
    "    float2 ab = ndcB - ndcA;\n"
    "    float2 cb = ndcB - ndcC;\n"
    "    float2 abn = normalize(float2(-ab.y, ab.x));\n"
    "    float2 cbn = -normalize(float2(-cb.y, cb.x));\n"
    "    \n"
    "    float sigma = sign(dot(ab + cb, yBasis));\n"
    "    if (abs(sigma) < 0.001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = in.color;\n"
    "        return out;\n"
    "    }\n"
    "    \n"
    "    float halfWidth = params.line_width * 0.5;\n"
    "    float id = in.template_pos.x;\n"
    "    float resolution = params.join_resolution;\n"
    "    \n"
    "    float2 offset;\n"
    "    \n"
    "    float cosTheta = clamp(dot(abn, cbn), -1.0, 1.0);\n"
    "    float theta = acos(cosTheta);\n"
    "    \n"
    "    bool useSemicircle = (theta > params.miter_angle_limit);\n"
    "    \n"
    "    if (id < 0.5) {\n"
    "        if (useSemicircle) {\n"
    "            offset = float2(0.0, 0.0);\n"
    "        } else {\n"
    "            float dotYBasisAbn = dot(yBasis, abn);\n"
    "            if (abs(dotYBasisAbn) < 0.001) dotYBasisAbn = 0.001;\n"
    "            offset = -halfWidth * yBasis * sigma / dotYBasisAbn;\n"
    "        }\n"
    "    } else {\n"
    "        float vertexAngle = (sigma * 0.5 * PI) + (-0.5 * theta) + (theta * (id - 1.0) / resolution);\n"
    "        float2 pos = halfWidth * float2(cos(vertexAngle), sin(vertexAngle));\n"
    "        offset = xBasis * pos.x + yBasis * pos.y;\n"
    "    }\n"
    "    \n"
    "    offset.x /= params.aspect_ratio;\n"
    "    \n"
    "    out.pos = clipB;\n"
    "    out.pos.xy += offset * clipB.w;\n"
    "    out.color = in.color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_pie_join_fs_source =
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "struct fs_in {\n"
    "    float4 color;\n"
    "};\n"
    "fragment float4 fs_main(fs_in in [[stage_in]]) {\n"
    "    return in.color;\n"
    "}\n";

//------------------------------------------------------------------------------
// OpenGL 3.3 GLSL
//------------------------------------------------------------------------------
#elif defined(SOKOL_GLCORE)

//--- Intermediate segment shader ---
static const char* alpha_intermediate_segment_vs_source =
    "#version 330\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec3 pD;\n"
    "layout(location=5) in vec4 color;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec4 clipD = mvp * vec4(pD, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    vec2 ndcD = clipD.xy / clipD.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    ndcD.x *= aspect_ratio;\n"
    "    vec2 p0, p1, p2;\n"
    "    vec2 pos = vec2(template_pos.z, template_pos.y);\n"
    "    vec4 baseClip;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        p0 = ndcA; p1 = ndcB; p2 = ndcC;\n"
    "        baseClip = clipB;\n"
    "    } else {\n"
    "        p0 = ndcD; p1 = ndcC; p2 = ndcB;\n"
    "        pos = vec2(1.0 - template_pos.z, -template_pos.y);\n"
    "        baseClip = clipC;\n"
    "    }\n"
    "    vec2 d01 = p1 - p0;\n"
    "    vec2 d21 = p1 - p2;\n"
    "    vec2 d12 = p2 - p1;\n"
    "    float len01 = length(d01);\n"
    "    float len12 = length(d12);\n"
    "    vec2 dir01 = (len01 > 0.0001) ? d01 / len01 : vec2(1.0, 0.0);\n"
    "    vec2 dir12 = (len12 > 0.0001) ? d12 / len12 : vec2(1.0, 0.0);\n"
    "    vec2 tangentSum = dir01 + dir12;\n"
    "    float tangentLen = length(tangentSum);\n"
    "    vec2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : vec2(-dir01.y, dir01.x);\n"
    "    vec2 normal = vec2(-tangent.y, tangent.x);\n"
    "    vec2 p01Norm = vec2(-dir01.y, dir01.x);\n"
    "    float sigma = sign(dot(d01 + d21, normal));\n"
    "    if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "    float dotNP = dot(normal, p01Norm);\n"
    "    float minDot = 0.1;\n"
    "    if (abs(dotNP) < minDot) {\n"
    "        dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "    }\n"
    "    vec2 offset;\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    if (sign(pos.y) == -sigma) {\n"
    "        offset = normal * (-sigma) * halfWidth / dotNP;\n"
    "    } else {\n"
    "        vec2 yBasis = vec2(-dir12.y, dir12.x);\n"
    "        offset = yBasis * line_width * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = baseClip;\n"
    "    gl_Position.xy += offset * baseClip.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_intermediate_segment_fs_source =
    "#version 330\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//--- Terminal segment shader ---
static const char* alpha_terminal_segment_vs_source =
    "#version 330\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec4 color;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    vec2 dAB = ndcB - ndcA;\n"
    "    float lenAB = length(dAB);\n"
    "    vec2 dirAB = (lenAB > 0.0001) ? dAB / lenAB : vec2(1.0, 0.0);\n"
    "    vec2 perp = vec2(-dirAB.y, dirAB.x);\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    vec2 offset;\n"
    "    vec4 baseClip;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        baseClip = clipA;\n"
    "        offset = perp * line_width * template_pos.y;\n"
    "    } else {\n"
    "        baseClip = clipB;\n"
    "        vec2 dBC = ndcC - ndcB;\n"
    "        float lenBC = length(dBC);\n"
    "        vec2 dirBC = (lenBC > 0.0001) ? dBC / lenBC : vec2(1.0, 0.0);\n"
    "        vec2 tangentSum = dirAB + dirBC;\n"
    "        float tangentLen = length(tangentSum);\n"
    "        vec2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : vec2(-dirAB.y, dirAB.x);\n"
    "        vec2 normal = vec2(-tangent.y, tangent.x);\n"
    "        vec2 abNorm = vec2(-dirAB.y, dirAB.x);\n"
    "        vec2 ab = dAB;\n"
    "        vec2 cb = -dBC;\n"
    "        float sigma = sign(dot(ab + cb, normal));\n"
    "        if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "        float dotNP = dot(normal, abNorm);\n"
    "        float minDot = 0.1;\n"
    "        if (abs(dotNP) < minDot) {\n"
    "            dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "        }\n"
    "        float posY = template_pos.y;\n"
    "        if (sign(posY) == -sigma) {\n"
    "            offset = 0.5 * normal * (-sigma) * line_width / dotNP;\n"
    "        } else {\n"
    "            vec2 yBasis = vec2(-dirAB.y, dirAB.x);\n"
    "            offset = yBasis * line_width * posY;\n"
    "        }\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = baseClip;\n"
    "    gl_Position.xy += offset * baseClip.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_terminal_segment_fs_source =
    "#version 330\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//--- Pie-slice join shader ---
static const char* alpha_pie_join_vs_source =
    "#version 330\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "uniform float join_resolution;\n"
    "uniform float miter_angle_limit;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec4 color;\n"
    "out vec4 v_color;\n"
    "const float PI = 3.14159265359;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    vec2 dirBC = ndcC - ndcB;\n"
    "    vec2 dirBA = ndcA - ndcB;\n"
    "    float lenBC = length(dirBC);\n"
    "    float lenBA = length(dirBA);\n"
    "    if (lenBC < 0.0001 || lenBA < 0.0001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    vec2 normBC = dirBC / lenBC;\n"
    "    vec2 normBA = dirBA / lenBA;\n"
    "    vec2 xBasisSum = normBC - normBA;\n"
    "    float xBasisLen = length(xBasisSum);\n"
    "    if (xBasisLen < 0.0001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    vec2 xBasis = xBasisSum / xBasisLen;\n"
    "    vec2 yBasis = vec2(-xBasis.y, xBasis.x);\n"
    "    vec2 ab = ndcB - ndcA;\n"
    "    vec2 cb = ndcB - ndcC;\n"
    "    vec2 abn = normalize(vec2(-ab.y, ab.x));\n"
    "    vec2 cbn = -normalize(vec2(-cb.y, cb.x));\n"
    "    float sigma = sign(dot(ab + cb, yBasis));\n"
    "    if (abs(sigma) < 0.001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    float id = template_pos.x;\n"
    "    float resolution = join_resolution;\n"
    "    vec2 offset;\n"
    "    float cosTheta = clamp(dot(abn, cbn), -1.0, 1.0);\n"
    "    float theta = acos(cosTheta);\n"
    "    bool useSemicircle = (theta > miter_angle_limit);\n"
    "    if (id < 0.5) {\n"
    "        if (useSemicircle) {\n"
    "            offset = vec2(0.0, 0.0);\n"
    "        } else {\n"
    "            float dotYBasisAbn = dot(yBasis, abn);\n"
    "            if (abs(dotYBasisAbn) < 0.001) dotYBasisAbn = 0.001;\n"
    "            offset = -halfWidth * yBasis * sigma / dotYBasisAbn;\n"
    "        }\n"
    "    } else {\n"
    "        float vertexAngle = (sigma * 0.5 * PI) + (-0.5 * theta) + (theta * (id - 1.0) / resolution);\n"
    "        vec2 pos = halfWidth * vec2(cos(vertexAngle), sin(vertexAngle));\n"
    "        offset = xBasis * pos.x + yBasis * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = clipB;\n"
    "    gl_Position.xy += offset * clipB.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_pie_join_fs_source =
    "#version 330\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//------------------------------------------------------------------------------
// OpenGL ES 3.0 GLSL (Android)
//------------------------------------------------------------------------------
#elif defined(SOKOL_GLES3)

//--- Intermediate segment shader ---
static const char* alpha_intermediate_segment_vs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec3 pD;\n"
    "layout(location=5) in vec4 color;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec4 clipD = mvp * vec4(pD, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    vec2 ndcD = clipD.xy / clipD.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    ndcD.x *= aspect_ratio;\n"
    "    vec2 p0, p1, p2;\n"
    "    vec2 pos = vec2(template_pos.z, template_pos.y);\n"
    "    vec4 baseClip;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        p0 = ndcA; p1 = ndcB; p2 = ndcC;\n"
    "        baseClip = clipB;\n"
    "    } else {\n"
    "        p0 = ndcD; p1 = ndcC; p2 = ndcB;\n"
    "        pos = vec2(1.0 - template_pos.z, -template_pos.y);\n"
    "        baseClip = clipC;\n"
    "    }\n"
    "    vec2 d01 = p1 - p0;\n"
    "    vec2 d21 = p1 - p2;\n"
    "    vec2 d12 = p2 - p1;\n"
    "    float len01 = length(d01);\n"
    "    float len12 = length(d12);\n"
    "    vec2 dir01 = (len01 > 0.0001) ? d01 / len01 : vec2(1.0, 0.0);\n"
    "    vec2 dir12 = (len12 > 0.0001) ? d12 / len12 : vec2(1.0, 0.0);\n"
    "    vec2 tangentSum = dir01 + dir12;\n"
    "    float tangentLen = length(tangentSum);\n"
    "    vec2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : vec2(-dir01.y, dir01.x);\n"
    "    vec2 normal = vec2(-tangent.y, tangent.x);\n"
    "    vec2 p01Norm = vec2(-dir01.y, dir01.x);\n"
    "    float sigma = sign(dot(d01 + d21, normal));\n"
    "    if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "    float dotNP = dot(normal, p01Norm);\n"
    "    float minDot = 0.1;\n"
    "    if (abs(dotNP) < minDot) {\n"
    "        dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "    }\n"
    "    vec2 offset;\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    if (sign(pos.y) == -sigma) {\n"
    "        offset = normal * (-sigma) * halfWidth / dotNP;\n"
    "    } else {\n"
    "        vec2 yBasis = vec2(-dir12.y, dir12.x);\n"
    "        offset = yBasis * line_width * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = baseClip;\n"
    "    gl_Position.xy += offset * baseClip.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_intermediate_segment_fs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//--- Terminal segment shader ---
static const char* alpha_terminal_segment_vs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec4 color;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    vec2 dAB = ndcB - ndcA;\n"
    "    float lenAB = length(dAB);\n"
    "    vec2 dirAB = (lenAB > 0.0001) ? dAB / lenAB : vec2(1.0, 0.0);\n"
    "    vec2 perp = vec2(-dirAB.y, dirAB.x);\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    vec2 offset;\n"
    "    vec4 baseClip;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        baseClip = clipA;\n"
    "        offset = perp * line_width * template_pos.y;\n"
    "    } else {\n"
    "        baseClip = clipB;\n"
    "        vec2 dBC = ndcC - ndcB;\n"
    "        float lenBC = length(dBC);\n"
    "        vec2 dirBC = (lenBC > 0.0001) ? dBC / lenBC : vec2(1.0, 0.0);\n"
    "        vec2 tangentSum = dirAB + dirBC;\n"
    "        float tangentLen = length(tangentSum);\n"
    "        vec2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : vec2(-dirAB.y, dirAB.x);\n"
    "        vec2 normal = vec2(-tangent.y, tangent.x);\n"
    "        vec2 abNorm = vec2(-dirAB.y, dirAB.x);\n"
    "        vec2 ab = dAB;\n"
    "        vec2 cb = -dBC;\n"
    "        float sigma = sign(dot(ab + cb, normal));\n"
    "        if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "        float dotNP = dot(normal, abNorm);\n"
    "        float minDot = 0.1;\n"
    "        if (abs(dotNP) < minDot) {\n"
    "            dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "        }\n"
    "        float posY = template_pos.y;\n"
    "        if (sign(posY) == -sigma) {\n"
    "            offset = 0.5 * normal * (-sigma) * line_width / dotNP;\n"
    "        } else {\n"
    "            vec2 yBasis = vec2(-dirAB.y, dirAB.x);\n"
    "            offset = yBasis * line_width * posY;\n"
    "        }\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = baseClip;\n"
    "    gl_Position.xy += offset * baseClip.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_terminal_segment_fs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//--- Pie-slice join shader ---
static const char* alpha_pie_join_vs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "uniform mat4 mvp;\n"
    "uniform float line_width;\n"
    "uniform float aspect_ratio;\n"
    "uniform float join_resolution;\n"
    "uniform float miter_angle_limit;\n"
    "layout(location=0) in vec3 template_pos;\n"
    "layout(location=1) in vec3 pA;\n"
    "layout(location=2) in vec3 pB;\n"
    "layout(location=3) in vec3 pC;\n"
    "layout(location=4) in vec4 color;\n"
    "out vec4 v_color;\n"
    "const float PI = 3.14159265359;\n"
    "void main() {\n"
    "    vec4 clipA = mvp * vec4(pA, 1.0);\n"
    "    vec4 clipB = mvp * vec4(pB, 1.0);\n"
    "    vec4 clipC = mvp * vec4(pC, 1.0);\n"
    "    vec2 ndcA = clipA.xy / clipA.w;\n"
    "    vec2 ndcB = clipB.xy / clipB.w;\n"
    "    vec2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    vec2 dirBC = ndcC - ndcB;\n"
    "    vec2 dirBA = ndcA - ndcB;\n"
    "    float lenBC = length(dirBC);\n"
    "    float lenBA = length(dirBA);\n"
    "    if (lenBC < 0.0001 || lenBA < 0.0001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    vec2 normBC = dirBC / lenBC;\n"
    "    vec2 normBA = dirBA / lenBA;\n"
    "    vec2 xBasisSum = normBC - normBA;\n"
    "    float xBasisLen = length(xBasisSum);\n"
    "    if (xBasisLen < 0.0001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    vec2 xBasis = xBasisSum / xBasisLen;\n"
    "    vec2 yBasis = vec2(-xBasis.y, xBasis.x);\n"
    "    vec2 ab = ndcB - ndcA;\n"
    "    vec2 cb = ndcB - ndcC;\n"
    "    vec2 abn = normalize(vec2(-ab.y, ab.x));\n"
    "    vec2 cbn = -normalize(vec2(-cb.y, cb.x));\n"
    "    float sigma = sign(dot(ab + cb, yBasis));\n"
    "    if (abs(sigma) < 0.001) {\n"
    "        gl_Position = clipB;\n"
    "        v_color = color;\n"
    "        return;\n"
    "    }\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    float id = template_pos.x;\n"
    "    float resolution = join_resolution;\n"
    "    vec2 offset;\n"
    "    float cosTheta = clamp(dot(abn, cbn), -1.0, 1.0);\n"
    "    float theta = acos(cosTheta);\n"
    "    bool useSemicircle = (theta > miter_angle_limit);\n"
    "    if (id < 0.5) {\n"
    "        if (useSemicircle) {\n"
    "            offset = vec2(0.0, 0.0);\n"
    "        } else {\n"
    "            float dotYBasisAbn = dot(yBasis, abn);\n"
    "            if (abs(dotYBasisAbn) < 0.001) dotYBasisAbn = 0.001;\n"
    "            offset = -halfWidth * yBasis * sigma / dotYBasisAbn;\n"
    "        }\n"
    "    } else {\n"
    "        float vertexAngle = (sigma * 0.5 * PI) + (-0.5 * theta) + (theta * (id - 1.0) / resolution);\n"
    "        vec2 pos = halfWidth * vec2(cos(vertexAngle), sin(vertexAngle));\n"
    "        offset = xBasis * pos.x + yBasis * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    gl_Position = clipB;\n"
    "    gl_Position.xy += offset * clipB.w;\n"
    "    v_color = color;\n"
    "}\n";

static const char* alpha_pie_join_fs_source =
    "#version 300 es\n"
    "precision highp float;\n"
    "in vec4 v_color;\n"
    "out vec4 frag_color;\n"
    "void main() {\n"
    "    frag_color = v_color;\n"
    "}\n";

//------------------------------------------------------------------------------
// WebGPU WGSL
//------------------------------------------------------------------------------
#elif defined(SOKOL_WGPU)

//--- Intermediate segment shader ---
static const char* alpha_intermediate_segment_vs_source =
    "struct vs_params {\n"
    "    mvp: mat4x4<f32>,\n"
    "    line_width: f32,\n"
    "    aspect_ratio: f32,\n"
    "};\n"
    "@group(0) @binding(0) var<uniform> params: vs_params;\n"
    "struct vs_out {\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) color: vec4<f32>,\n"
    "};\n"
    "@vertex\n"
    "fn vs_main(\n"
    "    @location(0) template_pos: vec3<f32>,\n"
    "    @location(1) pA: vec3<f32>,\n"
    "    @location(2) pB: vec3<f32>,\n"
    "    @location(3) pC: vec3<f32>,\n"
    "    @location(4) pD: vec3<f32>,\n"
    "    @location(5) color: vec4<f32>\n"
    ") -> vs_out {\n"
    "    var out: vs_out;\n"
    "    let clipA = params.mvp * vec4<f32>(pA, 1.0);\n"
    "    let clipB = params.mvp * vec4<f32>(pB, 1.0);\n"
    "    let clipC = params.mvp * vec4<f32>(pC, 1.0);\n"
    "    let clipD = params.mvp * vec4<f32>(pD, 1.0);\n"
    "    var ndcA = clipA.xy / clipA.w;\n"
    "    var ndcB = clipB.xy / clipB.w;\n"
    "    var ndcC = clipC.xy / clipC.w;\n"
    "    var ndcD = clipD.xy / clipD.w;\n"
    "    ndcA.x = ndcA.x * params.aspect_ratio;\n"
    "    ndcB.x = ndcB.x * params.aspect_ratio;\n"
    "    ndcC.x = ndcC.x * params.aspect_ratio;\n"
    "    ndcD.x = ndcD.x * params.aspect_ratio;\n"
    "    var p0: vec2<f32>; var p1: vec2<f32>; var p2: vec2<f32>;\n"
    "    var pos: vec2<f32>;\n"
    "    var baseClip: vec4<f32>;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        p0 = ndcA; p1 = ndcB; p2 = ndcC;\n"
    "        pos = vec2<f32>(template_pos.z, template_pos.y);\n"
    "        baseClip = clipB;\n"
    "    } else {\n"
    "        p0 = ndcD; p1 = ndcC; p2 = ndcB;\n"
    "        pos = vec2<f32>(1.0 - template_pos.z, -template_pos.y);\n"
    "        baseClip = clipC;\n"
    "    }\n"
    "    let d01 = p1 - p0;\n"
    "    let d21 = p1 - p2;\n"
    "    let d12 = p2 - p1;\n"
    "    let len01 = length(d01);\n"
    "    let len12 = length(d12);\n"
    "    var dir01: vec2<f32>; var dir12: vec2<f32>;\n"
    "    if (len01 > 0.0001) { dir01 = d01 / len01; } else { dir01 = vec2<f32>(1.0, 0.0); }\n"
    "    if (len12 > 0.0001) { dir12 = d12 / len12; } else { dir12 = vec2<f32>(1.0, 0.0); }\n"
    "    let tangentSum = dir01 + dir12;\n"
    "    let tangentLen = length(tangentSum);\n"
    "    var tangent: vec2<f32>;\n"
    "    if (tangentLen > 0.0001) { tangent = tangentSum / tangentLen; } else { tangent = vec2<f32>(-dir01.y, dir01.x); }\n"
    "    let normal = vec2<f32>(-tangent.y, tangent.x);\n"
    "    let p01Norm = vec2<f32>(-dir01.y, dir01.x);\n"
    "    var sigma = sign(dot(d01 + d21, normal));\n"
    "    if (abs(sigma) < 0.001) { sigma = 1.0; }\n"
    "    var dotNP = dot(normal, p01Norm);\n"
    "    let minDot = 0.1;\n"
    "    if (abs(dotNP) < minDot) {\n"
    "        if (dotNP >= 0.0) { dotNP = minDot; } else { dotNP = -minDot; }\n"
    "    }\n"
    "    var offset: vec2<f32>;\n"
    "    let halfWidth = params.line_width * 0.5;\n"
    "    if (sign(pos.y) == -sigma) {\n"
    "        offset = normal * (-sigma) * halfWidth / dotNP;\n"
    "    } else {\n"
    "        let yBasis = vec2<f32>(-dir12.y, dir12.x);\n"
    "        offset = yBasis * params.line_width * pos.y;\n"
    "    }\n"
    "    offset.x = offset.x / params.aspect_ratio;\n"
    "    out.pos = baseClip;\n"
    "    out.pos.x = out.pos.x + offset.x * baseClip.w;\n"
    "    out.pos.y = out.pos.y + offset.y * baseClip.w;\n"
    "    out.color = color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_intermediate_segment_fs_source =
    "@fragment\n"
    "fn fs_main(@location(0) color: vec4<f32>) -> @location(0) vec4<f32> {\n"
    "    return color;\n"
    "}\n";

//--- Terminal segment shader ---
static const char* alpha_terminal_segment_vs_source =
    "struct vs_params {\n"
    "    mvp: mat4x4<f32>,\n"
    "    line_width: f32,\n"
    "    aspect_ratio: f32,\n"
    "};\n"
    "@group(0) @binding(0) var<uniform> params: vs_params;\n"
    "struct vs_out {\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) color: vec4<f32>,\n"
    "};\n"
    "@vertex\n"
    "fn vs_main(\n"
    "    @location(0) template_pos: vec3<f32>,\n"
    "    @location(1) pA: vec3<f32>,\n"
    "    @location(2) pB: vec3<f32>,\n"
    "    @location(3) pC: vec3<f32>,\n"
    "    @location(4) color: vec4<f32>\n"
    ") -> vs_out {\n"
    "    var out: vs_out;\n"
    "    let clipA = params.mvp * vec4<f32>(pA, 1.0);\n"
    "    let clipB = params.mvp * vec4<f32>(pB, 1.0);\n"
    "    let clipC = params.mvp * vec4<f32>(pC, 1.0);\n"
    "    var ndcA = clipA.xy / clipA.w;\n"
    "    var ndcB = clipB.xy / clipB.w;\n"
    "    var ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x = ndcA.x * params.aspect_ratio;\n"
    "    ndcB.x = ndcB.x * params.aspect_ratio;\n"
    "    ndcC.x = ndcC.x * params.aspect_ratio;\n"
    "    let dAB = ndcB - ndcA;\n"
    "    let lenAB = length(dAB);\n"
    "    var dirAB: vec2<f32>;\n"
    "    if (lenAB > 0.0001) { dirAB = dAB / lenAB; } else { dirAB = vec2<f32>(1.0, 0.0); }\n"
    "    let perp = vec2<f32>(-dirAB.y, dirAB.x);\n"
    "    let halfWidth = params.line_width * 0.5;\n"
    "    var offset: vec2<f32>;\n"
    "    var baseClip: vec4<f32>;\n"
    "    if (template_pos.z < 0.5) {\n"
    "        baseClip = clipA;\n"
    "        offset = perp * params.line_width * template_pos.y;\n"
    "    } else {\n"
    "        baseClip = clipB;\n"
    "        let dBC = ndcC - ndcB;\n"
    "        let lenBC = length(dBC);\n"
    "        var dirBC: vec2<f32>;\n"
    "        if (lenBC > 0.0001) { dirBC = dBC / lenBC; } else { dirBC = vec2<f32>(1.0, 0.0); }\n"
    "        let tangentSum = dirAB + dirBC;\n"
    "        let tangentLen = length(tangentSum);\n"
    "        var tangent: vec2<f32>;\n"
    "        if (tangentLen > 0.0001) { tangent = tangentSum / tangentLen; } else { tangent = vec2<f32>(-dirAB.y, dirAB.x); }\n"
    "        let normal = vec2<f32>(-tangent.y, tangent.x);\n"
    "        let abNorm = vec2<f32>(-dirAB.y, dirAB.x);\n"
    "        let ab = dAB;\n"
    "        let cb = -dBC;\n"
    "        var sigma = sign(dot(ab + cb, normal));\n"
    "        if (abs(sigma) < 0.001) { sigma = 1.0; }\n"
    "        var dotNP = dot(normal, abNorm);\n"
    "        let minDot = 0.1;\n"
    "        if (abs(dotNP) < minDot) {\n"
    "            if (dotNP >= 0.0) { dotNP = minDot; } else { dotNP = -minDot; }\n"
    "        }\n"
    "        let posY = template_pos.y;\n"
    "        if (sign(posY) == -sigma) {\n"
    "            offset = 0.5 * normal * (-sigma) * params.line_width / dotNP;\n"
    "        } else {\n"
    "            let yBasis = vec2<f32>(-dirAB.y, dirAB.x);\n"
    "            offset = yBasis * params.line_width * posY;\n"
    "        }\n"
    "    }\n"
    "    offset.x = offset.x / params.aspect_ratio;\n"
    "    out.pos = baseClip;\n"
    "    out.pos.x = out.pos.x + offset.x * baseClip.w;\n"
    "    out.pos.y = out.pos.y + offset.y * baseClip.w;\n"
    "    out.color = color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_terminal_segment_fs_source =
    "@fragment\n"
    "fn fs_main(@location(0) color: vec4<f32>) -> @location(0) vec4<f32> {\n"
    "    return color;\n"
    "}\n";

//--- Pie-slice join shader ---
static const char* alpha_pie_join_vs_source =
    "struct vs_params {\n"
    "    mvp: mat4x4<f32>,\n"
    "    line_width: f32,\n"
    "    aspect_ratio: f32,\n"
    "    join_resolution: f32,\n"
    "    miter_angle_limit: f32,\n"
    "};\n"
    "@group(0) @binding(0) var<uniform> params: vs_params;\n"
    "struct vs_out {\n"
    "    @builtin(position) pos: vec4<f32>,\n"
    "    @location(0) color: vec4<f32>,\n"
    "};\n"
    "const PI: f32 = 3.14159265359;\n"
    "@vertex\n"
    "fn vs_main(\n"
    "    @location(0) template_pos: vec3<f32>,\n"
    "    @location(1) pA: vec3<f32>,\n"
    "    @location(2) pB: vec3<f32>,\n"
    "    @location(3) pC: vec3<f32>,\n"
    "    @location(4) color: vec4<f32>\n"
    ") -> vs_out {\n"
    "    var out: vs_out;\n"
    "    let clipA = params.mvp * vec4<f32>(pA, 1.0);\n"
    "    let clipB = params.mvp * vec4<f32>(pB, 1.0);\n"
    "    let clipC = params.mvp * vec4<f32>(pC, 1.0);\n"
    "    var ndcA = clipA.xy / clipA.w;\n"
    "    var ndcB = clipB.xy / clipB.w;\n"
    "    var ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x = ndcA.x * params.aspect_ratio;\n"
    "    ndcB.x = ndcB.x * params.aspect_ratio;\n"
    "    ndcC.x = ndcC.x * params.aspect_ratio;\n"
    "    let dirBC = ndcC - ndcB;\n"
    "    let dirBA = ndcA - ndcB;\n"
    "    let lenBC = length(dirBC);\n"
    "    let lenBA = length(dirBA);\n"
    "    if (lenBC < 0.0001 || lenBA < 0.0001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = color;\n"
    "        return out;\n"
    "    }\n"
    "    let normBC = dirBC / lenBC;\n"
    "    let normBA = dirBA / lenBA;\n"
    "    let xBasisSum = normBC - normBA;\n"
    "    let xBasisLen = length(xBasisSum);\n"
    "    if (xBasisLen < 0.0001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = color;\n"
    "        return out;\n"
    "    }\n"
    "    let xBasis = xBasisSum / xBasisLen;\n"
    "    let yBasis = vec2<f32>(-xBasis.y, xBasis.x);\n"
    "    let ab = ndcB - ndcA;\n"
    "    let cb = ndcB - ndcC;\n"
    "    let abn = normalize(vec2<f32>(-ab.y, ab.x));\n"
    "    let cbn = -normalize(vec2<f32>(-cb.y, cb.x));\n"
    "    var sigma = sign(dot(ab + cb, yBasis));\n"
    "    if (abs(sigma) < 0.001) {\n"
    "        out.pos = clipB;\n"
    "        out.color = color;\n"
    "        return out;\n"
    "    }\n"
    "    let halfWidth = params.line_width * 0.5;\n"
    "    let id = template_pos.x;\n"
    "    let resolution = params.join_resolution;\n"
    "    var offset: vec2<f32>;\n"
    "    let cosTheta = clamp(dot(abn, cbn), -1.0, 1.0);\n"
    "    let theta = acos(cosTheta);\n"
    "    let useSemicircle = (theta > params.miter_angle_limit);\n"
    "    if (id < 0.5) {\n"
    "        if (useSemicircle) {\n"
    "            offset = vec2<f32>(0.0, 0.0);\n"
    "        } else {\n"
    "            var dotYBasisAbn = dot(yBasis, abn);\n"
    "            if (abs(dotYBasisAbn) < 0.001) { dotYBasisAbn = 0.001; }\n"
    "            offset = -halfWidth * yBasis * sigma / dotYBasisAbn;\n"
    "        }\n"
    "    } else {\n"
    "        let vertexAngle = (sigma * 0.5 * PI) + (-0.5 * theta) + (theta * (id - 1.0) / resolution);\n"
    "        let pos = halfWidth * vec2<f32>(cos(vertexAngle), sin(vertexAngle));\n"
    "        offset = xBasis * pos.x + yBasis * pos.y;\n"
    "    }\n"
    "    offset.x = offset.x / params.aspect_ratio;\n"
    "    out.pos = clipB;\n"
    "    out.pos.x = out.pos.x + offset.x * clipB.w;\n"
    "    out.pos.y = out.pos.y + offset.y * clipB.w;\n"
    "    out.color = color;\n"
    "    return out;\n"
    "}\n";

static const char* alpha_pie_join_fs_source =
    "@fragment\n"
    "fn fs_main(@location(0) color: vec4<f32>) -> @location(0) vec4<f32> {\n"
    "    return color;\n"
    "}\n";

//------------------------------------------------------------------------------
// DirectX 11 HLSL
//------------------------------------------------------------------------------
#elif defined(SOKOL_D3D11)

//--- Intermediate segment shader ---
static const char* alpha_intermediate_segment_vs_source =
    "cbuffer vs_params : register(b0) {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "};\n"
    "struct vs_in {\n"
    "    float3 template_pos : POSITION;\n"
    "    float3 pA : TEXCOORD0;\n"
    "    float3 pB : TEXCOORD1;\n"
    "    float3 pC : TEXCOORD2;\n"
    "    float3 pD : TEXCOORD3;\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 color : COLOR;\n"
    "    float4 pos : SV_Position;\n"
    "};\n"
    "vs_out main(vs_in inp) {\n"
    "    vs_out outp;\n"
    "    float4 clipA = mul(mvp, float4(inp.pA, 1.0));\n"
    "    float4 clipB = mul(mvp, float4(inp.pB, 1.0));\n"
    "    float4 clipC = mul(mvp, float4(inp.pC, 1.0));\n"
    "    float4 clipD = mul(mvp, float4(inp.pD, 1.0));\n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    float2 ndcD = clipD.xy / clipD.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    ndcD.x *= aspect_ratio;\n"
    "    float2 p0, p1, p2;\n"
    "    float2 pos;\n"
    "    float4 baseClip;\n"
    "    if (inp.template_pos.z < 0.5) {\n"
    "        p0 = ndcA; p1 = ndcB; p2 = ndcC;\n"
    "        pos = float2(inp.template_pos.z, inp.template_pos.y);\n"
    "        baseClip = clipB;\n"
    "    } else {\n"
    "        p0 = ndcD; p1 = ndcC; p2 = ndcB;\n"
    "        pos = float2(1.0 - inp.template_pos.z, -inp.template_pos.y);\n"
    "        baseClip = clipC;\n"
    "    }\n"
    "    float2 d01 = p1 - p0;\n"
    "    float2 d21 = p1 - p2;\n"
    "    float2 d12 = p2 - p1;\n"
    "    float len01 = length(d01);\n"
    "    float len12 = length(d12);\n"
    "    float2 dir01 = (len01 > 0.0001) ? d01 / len01 : float2(1.0, 0.0);\n"
    "    float2 dir12 = (len12 > 0.0001) ? d12 / len12 : float2(1.0, 0.0);\n"
    "    float2 tangentSum = dir01 + dir12;\n"
    "    float tangentLen = length(tangentSum);\n"
    "    float2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : float2(-dir01.y, dir01.x);\n"
    "    float2 normal = float2(-tangent.y, tangent.x);\n"
    "    float2 p01Norm = float2(-dir01.y, dir01.x);\n"
    "    float sigma = sign(dot(d01 + d21, normal));\n"
    "    if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "    float dotNP = dot(normal, p01Norm);\n"
    "    float minDot = 0.1;\n"
    "    if (abs(dotNP) < minDot) {\n"
    "        dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "    }\n"
    "    float2 offset;\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    if (sign(pos.y) == -sigma) {\n"
    "        offset = normal * (-sigma) * halfWidth / dotNP;\n"
    "    } else {\n"
    "        float2 yBasis = float2(-dir12.y, dir12.x);\n"
    "        offset = yBasis * line_width * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    outp.pos = baseClip;\n"
    "    outp.pos.xy += offset * baseClip.w;\n"
    "    outp.color = inp.color;\n"
    "    return outp;\n"
    "}\n";

static const char* alpha_intermediate_segment_fs_source =
    "struct fs_in {\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "float4 main(fs_in inp) : SV_Target0 {\n"
    "    return inp.color;\n"
    "}\n";

//--- Terminal segment shader ---
static const char* alpha_terminal_segment_vs_source =
    "cbuffer vs_params : register(b0) {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "};\n"
    "struct vs_in {\n"
    "    float3 template_pos : POSITION;\n"
    "    float3 pA : TEXCOORD0;\n"
    "    float3 pB : TEXCOORD1;\n"
    "    float3 pC : TEXCOORD2;\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 color : COLOR;\n"
    "    float4 pos : SV_Position;\n"
    "};\n"
    "vs_out main(vs_in inp) {\n"
    "    vs_out outp;\n"
    "    float4 clipA = mul(mvp, float4(inp.pA, 1.0));\n"
    "    float4 clipB = mul(mvp, float4(inp.pB, 1.0));\n"
    "    float4 clipC = mul(mvp, float4(inp.pC, 1.0));\n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    float2 dAB = ndcB - ndcA;\n"
    "    float lenAB = length(dAB);\n"
    "    float2 dirAB = (lenAB > 0.0001) ? dAB / lenAB : float2(1.0, 0.0);\n"
    "    float2 perp = float2(-dirAB.y, dirAB.x);\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    float2 offset;\n"
    "    float4 baseClip;\n"
    "    if (inp.template_pos.z < 0.5) {\n"
    "        baseClip = clipA;\n"
    "        offset = perp * line_width * inp.template_pos.y;\n"
    "    } else {\n"
    "        baseClip = clipB;\n"
    "        float2 dBC = ndcC - ndcB;\n"
    "        float lenBC = length(dBC);\n"
    "        float2 dirBC = (lenBC > 0.0001) ? dBC / lenBC : float2(1.0, 0.0);\n"
    "        float2 tangentSum = dirAB + dirBC;\n"
    "        float tangentLen = length(tangentSum);\n"
    "        float2 tangent = (tangentLen > 0.0001) ? tangentSum / tangentLen : float2(-dirAB.y, dirAB.x);\n"
    "        float2 normal = float2(-tangent.y, tangent.x);\n"
    "        float2 abNorm = float2(-dirAB.y, dirAB.x);\n"
    "        float2 ab = dAB;\n"
    "        float2 cb = -dBC;\n"
    "        float sigma = sign(dot(ab + cb, normal));\n"
    "        if (abs(sigma) < 0.001) sigma = 1.0;\n"
    "        float dotNP = dot(normal, abNorm);\n"
    "        float minDot = 0.1;\n"
    "        if (abs(dotNP) < minDot) {\n"
    "            dotNP = (dotNP >= 0.0) ? minDot : -minDot;\n"
    "        }\n"
    "        float posY = inp.template_pos.y;\n"
    "        if (sign(posY) == -sigma) {\n"
    "            offset = 0.5 * normal * (-sigma) * line_width / dotNP;\n"
    "        } else {\n"
    "            float2 yBasis = float2(-dirAB.y, dirAB.x);\n"
    "            offset = yBasis * line_width * posY;\n"
    "        }\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    outp.pos = baseClip;\n"
    "    outp.pos.xy += offset * baseClip.w;\n"
    "    outp.color = inp.color;\n"
    "    return outp;\n"
    "}\n";

static const char* alpha_terminal_segment_fs_source =
    "struct fs_in {\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "float4 main(fs_in inp) : SV_Target0 {\n"
    "    return inp.color;\n"
    "}\n";

//--- Pie-slice join shader ---
static const char* alpha_pie_join_vs_source =
    "cbuffer vs_params : register(b0) {\n"
    "    float4x4 mvp;\n"
    "    float line_width;\n"
    "    float aspect_ratio;\n"
    "    float join_resolution;\n"
    "    float miter_angle_limit;\n"
    "};\n"
    "struct vs_in {\n"
    "    float3 template_pos : POSITION;\n"
    "    float3 pA : TEXCOORD0;\n"
    "    float3 pB : TEXCOORD1;\n"
    "    float3 pC : TEXCOORD2;\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "struct vs_out {\n"
    "    float4 color : COLOR;\n"
    "    float4 pos : SV_Position;\n"
    "};\n"
    "static const float PI = 3.14159265359;\n"
    "vs_out main(vs_in inp) {\n"
    "    vs_out outp;\n"
    "    float4 clipA = mul(mvp, float4(inp.pA, 1.0));\n"
    "    float4 clipB = mul(mvp, float4(inp.pB, 1.0));\n"
    "    float4 clipC = mul(mvp, float4(inp.pC, 1.0));\n"
    "    float2 ndcA = clipA.xy / clipA.w;\n"
    "    float2 ndcB = clipB.xy / clipB.w;\n"
    "    float2 ndcC = clipC.xy / clipC.w;\n"
    "    ndcA.x *= aspect_ratio;\n"
    "    ndcB.x *= aspect_ratio;\n"
    "    ndcC.x *= aspect_ratio;\n"
    "    float2 dirBC = ndcC - ndcB;\n"
    "    float2 dirBA = ndcA - ndcB;\n"
    "    float lenBC = length(dirBC);\n"
    "    float lenBA = length(dirBA);\n"
    "    if (lenBC < 0.0001 || lenBA < 0.0001) {\n"
    "        outp.pos = clipB;\n"
    "        outp.color = inp.color;\n"
    "        return outp;\n"
    "    }\n"
    "    float2 normBC = dirBC / lenBC;\n"
    "    float2 normBA = dirBA / lenBA;\n"
    "    float2 xBasisSum = normBC - normBA;\n"
    "    float xBasisLen = length(xBasisSum);\n"
    "    if (xBasisLen < 0.0001) {\n"
    "        outp.pos = clipB;\n"
    "        outp.color = inp.color;\n"
    "        return outp;\n"
    "    }\n"
    "    float2 xBasis = xBasisSum / xBasisLen;\n"
    "    float2 yBasis = float2(-xBasis.y, xBasis.x);\n"
    "    float2 ab = ndcB - ndcA;\n"
    "    float2 cb = ndcB - ndcC;\n"
    "    float2 abn = normalize(float2(-ab.y, ab.x));\n"
    "    float2 cbn = -normalize(float2(-cb.y, cb.x));\n"
    "    float sigma = sign(dot(ab + cb, yBasis));\n"
    "    if (abs(sigma) < 0.001) {\n"
    "        outp.pos = clipB;\n"
    "        outp.color = inp.color;\n"
    "        return outp;\n"
    "    }\n"
    "    float halfWidth = line_width * 0.5;\n"
    "    float id = inp.template_pos.x;\n"
    "    float resolution = join_resolution;\n"
    "    float2 offset;\n"
    "    float cosTheta = clamp(dot(abn, cbn), -1.0, 1.0);\n"
    "    float theta = acos(cosTheta);\n"
    "    bool useSemicircle = (theta > miter_angle_limit);\n"
    "    if (id < 0.5) {\n"
    "        if (useSemicircle) {\n"
    "            offset = float2(0.0, 0.0);\n"
    "        } else {\n"
    "            float dotYBasisAbn = dot(yBasis, abn);\n"
    "            if (abs(dotYBasisAbn) < 0.001) dotYBasisAbn = 0.001;\n"
    "            offset = -halfWidth * yBasis * sigma / dotYBasisAbn;\n"
    "        }\n"
    "    } else {\n"
    "        float vertexAngle = (sigma * 0.5 * PI) + (-0.5 * theta) + (theta * (id - 1.0) / resolution);\n"
    "        float2 pos = halfWidth * float2(cos(vertexAngle), sin(vertexAngle));\n"
    "        offset = xBasis * pos.x + yBasis * pos.y;\n"
    "    }\n"
    "    offset.x /= aspect_ratio;\n"
    "    outp.pos = clipB;\n"
    "    outp.pos.xy += offset * clipB.w;\n"
    "    outp.color = inp.color;\n"
    "    return outp;\n"
    "}\n";

static const char* alpha_pie_join_fs_source =
    "struct fs_in {\n"
    "    float4 color : COLOR;\n"
    "};\n"
    "float4 main(fs_in inp) : SV_Target0 {\n"
    "    return inp.color;\n"
    "}\n";

#else
#error "Unknown graphics backend - define SOKOL_GLCORE, SOKOL_GLES3, SOKOL_METAL, SOKOL_WGPU, or SOKOL_D3D11"
#endif

#endif // ALPHA_POLYLINE_SHADERS_H
