#!/usr/bin/env python3
"""
Convert OBJ mesh files to colored PLY files for testing in mdCAD.

Parses OBJ vertices and faces, generates random colors using various palettes,
and writes PLY output in ASCII or binary_little_endian format.

Usage:
    python obj_to_colored_ply.py input.obj output.ply
    python obj_to_colored_ply.py input.obj output.ply --color-mode face --palette pastel
    python obj_to_colored_ply.py input.obj output.ply --format binary --seed 42
"""

import argparse
import colorsys
import os
import random
import struct
import sys


def parse_obj(filepath):
    """Parse an OBJ file, returning vertices and triangulated faces.

    Handles face formats: f v, f v/vt, f v/vt/vn, f v//vn
    Quads and n-gons are fan-triangulated from the first vertex.

    Returns:
        vertices: list of (x, y, z) tuples
        faces: list of (i0, i1, i2) tuples (0-based indices)
    """
    vertices = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            parts = line.split()
            if not parts:
                continue

            if parts[0] == 'v' and len(parts) >= 4:
                x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                vertices.append((x, y, z))

            elif parts[0] == 'f' and len(parts) >= 4:
                # Parse face vertex indices (OBJ is 1-based)
                indices = []
                for token in parts[1:]:
                    # Handle v, v/vt, v/vt/vn, v//vn
                    vi = token.split('/')[0]
                    idx = int(vi)
                    # OBJ supports negative indices (relative to end)
                    if idx < 0:
                        idx = len(vertices) + idx
                    else:
                        idx -= 1  # Convert to 0-based
                    indices.append(idx)

                # Fan triangulation: triangle fan from first vertex
                for i in range(1, len(indices) - 1):
                    faces.append((indices[0], indices[i], indices[i + 1]))

    return vertices, faces


def generate_color_rainbow(rng):
    """Full HSV range, random hue, high saturation."""
    h = rng.random()
    s = 0.7 + rng.random() * 0.3  # 0.7-1.0
    v = 0.7 + rng.random() * 0.3  # 0.7-1.0
    r, g, b = colorsys.hsv_to_rgb(h, s, v)
    return int(r * 255), int(g * 255), int(b * 255)


def generate_color_pastel(rng):
    """Random hue, low saturation, high value."""
    h = rng.random()
    s = 0.2 + rng.random() * 0.3  # 0.2-0.5
    v = 0.8 + rng.random() * 0.2  # 0.8-1.0
    r, g, b = colorsys.hsv_to_rgb(h, s, v)
    return int(r * 255), int(g * 255), int(b * 255)


def generate_color_earth(rng):
    """Browns, greens, tans."""
    palette = [
        (0.08, 0.5, 0.7),  # Brown
        (0.10, 0.4, 0.6),  # Tan
        (0.12, 0.6, 0.5),  # Dark brown
        (0.25, 0.4, 0.6),  # Olive green
        (0.30, 0.3, 0.7),  # Sage
        (0.06, 0.5, 0.8),  # Sandy
        (0.15, 0.3, 0.5),  # Muted brown
        (0.35, 0.5, 0.5),  # Forest green
    ]
    h, s, v = rng.choice(palette)
    # Add slight variation
    h += (rng.random() - 0.5) * 0.03
    s += (rng.random() - 0.5) * 0.1
    v += (rng.random() - 0.5) * 0.1
    s = max(0, min(1, s))
    v = max(0, min(1, v))
    r, g, b = colorsys.hsv_to_rgb(h % 1.0, s, v)
    return int(r * 255), int(g * 255), int(b * 255)


def generate_color_grayscale(rng):
    """Random gray values."""
    v = rng.randint(40, 230)
    return v, v, v


COLOR_GENERATORS = {
    'rainbow': generate_color_rainbow,
    'pastel': generate_color_pastel,
    'earth': generate_color_earth,
    'grayscale': generate_color_grayscale,
}


def write_ply_ascii(filepath, vertices, faces, vertex_colors, face_colors, alpha):
    """Write PLY file in ASCII format."""
    has_vertex_colors = vertex_colors is not None
    has_face_colors = face_colors is not None
    alpha_byte = int(alpha * 255)

    with open(filepath, 'w') as f:
        # Header
        f.write("ply\n")
        f.write("format ascii 1.0\n")
        f.write(f"comment Generated by obj_to_colored_ply.py\n")
        f.write(f"element vertex {len(vertices)}\n")
        f.write("property float x\n")
        f.write("property float y\n")
        f.write("property float z\n")
        if has_vertex_colors:
            f.write("property uchar red\n")
            f.write("property uchar green\n")
            f.write("property uchar blue\n")
            f.write("property uchar alpha\n")
        f.write(f"element face {len(faces)}\n")
        f.write("property list uchar int vertex_indices\n")
        if has_face_colors:
            f.write("property uchar red\n")
            f.write("property uchar green\n")
            f.write("property uchar blue\n")
            f.write("property uchar alpha\n")
        f.write("end_header\n")

        # Vertices
        for i, (x, y, z) in enumerate(vertices):
            if has_vertex_colors:
                r, g, b = vertex_colors[i]
                f.write(f"{x:.6f} {y:.6f} {z:.6f} {r} {g} {b} {alpha_byte}\n")
            else:
                f.write(f"{x:.6f} {y:.6f} {z:.6f}\n")

        # Faces
        for i, (i0, i1, i2) in enumerate(faces):
            if has_face_colors:
                r, g, b = face_colors[i]
                f.write(f"3 {i0} {i1} {i2} {r} {g} {b} {alpha_byte}\n")
            else:
                f.write(f"3 {i0} {i1} {i2}\n")


def write_ply_binary(filepath, vertices, faces, vertex_colors, face_colors, alpha):
    """Write PLY file in binary_little_endian format."""
    has_vertex_colors = vertex_colors is not None
    has_face_colors = face_colors is not None
    alpha_byte = int(alpha * 255)

    with open(filepath, 'wb') as f:
        # Header (always ASCII text)
        header_lines = [
            "ply",
            "format binary_little_endian 1.0",
            "comment Generated by obj_to_colored_ply.py",
            f"element vertex {len(vertices)}",
            "property float x",
            "property float y",
            "property float z",
        ]
        if has_vertex_colors:
            header_lines += [
                "property uchar red",
                "property uchar green",
                "property uchar blue",
                "property uchar alpha",
            ]
        header_lines += [
            f"element face {len(faces)}",
            "property list uchar int vertex_indices",
        ]
        if has_face_colors:
            header_lines += [
                "property uchar red",
                "property uchar green",
                "property uchar blue",
                "property uchar alpha",
            ]
        header_lines.append("end_header")

        header = "\n".join(header_lines) + "\n"
        f.write(header.encode('ascii'))

        # Vertices (binary)
        for i, (x, y, z) in enumerate(vertices):
            f.write(struct.pack('<fff', x, y, z))
            if has_vertex_colors:
                r, g, b = vertex_colors[i]
                f.write(struct.pack('<BBBB', r, g, b, alpha_byte))

        # Faces (binary)
        for i, (i0, i1, i2) in enumerate(faces):
            f.write(struct.pack('<B', 3))  # vertex count
            f.write(struct.pack('<iii', i0, i1, i2))
            if has_face_colors:
                r, g, b = face_colors[i]
                f.write(struct.pack('<BBBB', r, g, b, alpha_byte))


def main():
    parser = argparse.ArgumentParser(
        description='Convert OBJ mesh files to colored PLY files.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Per-vertex rainbow colors (ASCII)
  python obj_to_colored_ply.py model.obj model.ply

  # Per-face pastel colors (ASCII)
  python obj_to_colored_ply.py model.obj model.ply --color-mode face --palette pastel

  # Binary output with reproducible colors
  python obj_to_colored_ply.py model.obj model.ply --format binary --seed 42

  # Earth-tone per-vertex colors with 50%% alpha
  python obj_to_colored_ply.py model.obj model.ply --palette earth --alpha 0.5

  # Grayscale per-face colors
  python obj_to_colored_ply.py model.obj model.ply --color-mode face --palette grayscale
"""
    )

    parser.add_argument('input', help='Input OBJ file path')
    parser.add_argument('output', help='Output PLY file path')
    parser.add_argument('--color-mode', choices=['vertex', 'face'], default='vertex',
                        help='Per-vertex or per-face random colors (default: vertex)')
    parser.add_argument('--format', choices=['ascii', 'binary'], default='ascii',
                        help='Output PLY format (default: ascii)')
    parser.add_argument('--seed', type=int, default=None,
                        help='Random seed for reproducible colors (default: random)')
    parser.add_argument('--palette', choices=['rainbow', 'pastel', 'earth', 'grayscale'],
                        default='rainbow',
                        help='Color palette (default: rainbow)')
    parser.add_argument('--alpha', type=float, default=1.0,
                        help='Alpha value 0-1 (default: 1.0)')

    args = parser.parse_args()

    # Validate inputs
    if not os.path.isfile(args.input):
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    if args.alpha < 0 or args.alpha > 1:
        print("Error: Alpha must be between 0 and 1", file=sys.stderr)
        sys.exit(1)

    # Parse OBJ
    print(f"Parsing OBJ: {args.input}")
    vertices, faces = parse_obj(args.input)

    if not vertices:
        print("Error: No vertices found in OBJ file", file=sys.stderr)
        sys.exit(1)

    if not faces:
        print("Error: No faces found in OBJ file", file=sys.stderr)
        sys.exit(1)

    print(f"  Vertices: {len(vertices):,}")
    print(f"  Faces (triangulated): {len(faces):,}")

    # Generate colors
    rng = random.Random(args.seed)
    color_fn = COLOR_GENERATORS[args.palette]

    vertex_colors = None
    face_colors = None

    if args.color_mode == 'vertex':
        vertex_colors = [color_fn(rng) for _ in vertices]
        print(f"  Generated {len(vertex_colors):,} vertex colors ({args.palette})")
    else:
        face_colors = [color_fn(rng) for _ in faces]
        print(f"  Generated {len(face_colors):,} face colors ({args.palette})")

    # Write PLY
    print(f"Writing PLY ({args.format}): {args.output}")

    if args.format == 'ascii':
        write_ply_ascii(args.output, vertices, faces, vertex_colors, face_colors, args.alpha)
    else:
        write_ply_binary(args.output, vertices, faces, vertex_colors, face_colors, args.alpha)

    # Report file size
    size = os.path.getsize(args.output)
    if size < 1024:
        size_str = f"{size} bytes"
    elif size < 1024 * 1024:
        size_str = f"{size / 1024:.1f} KB"
    else:
        size_str = f"{size / (1024 * 1024):.1f} MB"

    print(f"\nDone! {len(vertices):,} vertices, {len(faces):,} faces -> {args.output} ({size_str})")


if __name__ == '__main__':
    main()
